import { Inter } from "next/font/google";

// Styles
import "./globals.css";

// Components
import Navbar from "@/components/common/Navbar";
import HuddleContextProvider from "@/components/ClientComponents/HuddleContextProvider";
import { cn } from "@/utils/helpers";

import { WagmiConfig, createConfig } from "wagmi";
import { mainnet, polygon, optimism, arbitrum } from "wagmi/chains";
import { ConnectKitProvider, getDefaultConfig } from "connectkit";

const config = createConfig(
  getDefaultConfig({
    appName: "ConnectKit Next.js demo",
    infuraId: "de",
    alchemyId: "kkk",
    chains: [mainnet, polygon, optimism, arbitrum],
    walletConnectProjectId: "jj",
  })
);

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Audio Spaces Example App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen relative font-inter", inter.className)}>
        <Navbar />
        <WagmiConfig config={config}>
          <ConnectKitProvider>
            <HuddleContextProvider>{children}</HuddleContextProvider>
          </ConnectKitProvider>
        </WagmiConfig>
      </body>
    </html>
  );
}
